### ISSUE TITLE
Locked Medias

### ISSUE THREAD

**Issue by anaisponte** [GM-Alex/user-access-manager#103]
The management of medias make a 500 error appear whenever you try to access a file.
The RewriteBase rule of the generated .htaccess works back when a '/' is added before the folder name.

https://wordpress.org/support/topic/medias-locked/#post-9268700

**Comment by masimies** [comment]
Wow, you said it. I have been struggling with this same issue about months. Images are displaying now with slash before url path!
Yes, please Alex, fix this to next releases.

**Comment by masimies** [comment]
Tested this, and it seems to be working now.
Of course there comes something new all the time. This is not UAM issue, but someone could like the information.
I have raised up new issue for Ultimate Member with UAM:
https://github.com/ultimatemember/ultimatemember/issues/287

I think that this effect comes for all other plugins also with multisite-installation, what adds own files or folders to uploads root folder.

**Comment by masimies** [comment]
Hello,
Fixed this issue on UM-side.
But, UAM doesn't reach the subfolders, where is members data. Profile images are broken and upload is not allowed. There is no benefits, if i set members data to upload root because in case of hundreds of users, media item amount increases too much to be manageable. So this remains as my problem.
If there comes improvements some day for spread UAM protection to subfolders also.

br,

-matti

**Comment by masimies** [comment]
Hello,
Found a solution for this!
When UAM use WP Media functionality, you have to find a solution for it what covers subfolders under uploads-folder as well.
And one of this is https://fi.wordpress.org/plugins/media-library-plus/
This plugin scans all folders under Media Library and add them along WP-media.
And guess what, Now UAM can cover all medias. :-D
This works with Multisite-installation also. It does not work like file-manager, so if there comes new folders, you have to sync them manually.
@Alex, if you get this as a reference, you could make UAM work perfectly with this functionality, no matter of other plugin additional media-folder issue. If UAM could scan same way subfolders.

br,

-matti

**Comment by GM-Alex** [comment]
@masimies Great find. Thanks!

**Comment by masimies** [comment]
Well,
when one is fixed, another come on, uhhh.
Now the issue is with file upload. When trying to upload new profile image, the temp-file does not found when file-lock is on with 404-code. Without it, it loads the image.
Profile image is in subfolder of uploads:
/temp/NV290jb5OqMl67ZWQbHAb1yMXTmKjMl4hj7QXtMw/stream_photo_3acf694b4d082acae55c1660972aff85_5971b9ca3493c.jpg
Tried to change temp-folder to site temp, what does not have any .htaccess restrictions, but it was too hard job to figure out the whole code of it.
My security cam uploads works fine, as they are uploaded directly to webcam-folder and not use any temp-files in upload process.
Is that long name for the temporary image causing the issue or something else???
