### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by logemi** [GM-Alex/user-access-manager#105]
After installing UAM on a clean installation of my site, in Settings there is a Warning message in each section (Articles, Pages, Views, etc ...):
Warning: vsprintf(): Too few arguments in /homepages/6/d632330627/htdocs/immofizz/wp-content/plugins/user-access-manager/src/UserAccessManager/Controller/AdminSettingsController.php on line 232
![capture1](https://user-images.githubusercontent.com/29835951/27769706-581b26ac-5f30-11e7-8607-9ecf412c5006.JPG)

**Comment by GM-Alex** [comment]
This issue comes from an invalide translation. You can find the translation for your language here: https://translate.wordpress.org/projects/wp-plugins/user-access-manager

I only maintain German and English and since only the editors of for the languages have access to it, I'm not able to change it easily. Which language are you using? I will try to filter invalide translations.

**Comment by logemi** [comment]
I'm using French(France) language.
