### ISSUE TITLE
Plugin WPMC dont works with the latest update of UAM plugin

### ISSUE THREAD

**Issue by FredoMkb** [GM-Alex/user-access-manager#122]
Hello,

With the latest update of plugin UAM (v. 2.1.1), unfortunately, the plugin [WP Media Categories](https://fr.wordpress.org/plugins/wp-media-categories/) (v. 1.0.1) dont work anymore.

I need both of this plugins, can you fix that please ?

Thanks,
Regards,

Fredo

**Comment by GM-Alex** [comment]
What exactly doesn't work? How was the behavior before, how is it now?

**Comment by FredoMkb** [comment]
Hi, here two screenshots to visualize the issue :

[**Before update**](http://fredomkb.free.fr/public/wp/uam/UAM-1-Before-Update.png)

[**After update**](http://fredomkb.free.fr/public/wp/uam/UAM-2-After-Update.png)

Thanks

**Comment by GM-Alex** [comment]
@FredoMkb would it be possible to get FTP access and a backend user to your page to debug it? The plugin works for my test instance with the latest version, so I would investigate what's going on.

**Comment by GM-Alex** [comment]
Ok I would assume that at `YOURDIR/wp-content/plugins/wp-media-categories/wp-media-categories/includes/taxonomies.php` the taxonomy is changed form public to false: `'public' => false,` instead of `'public' => true,` at line 22. Could that be? That's the only thing what would make sense to me right now. If not FTP access would be great. Thanks a lot.

**Comment by FredoMkb** [comment]
Hello,

Sorry for not being able to answer earlier, but I just update the plugin with the latest fix, version 2.1.2, and everything seems to be in order with the WP Media Categories plugin.

Thank you very much for your work and reactivity, it is very appreciable!

Regards,

Fredo
