### ISSUE TITLE
After latest Update Problems with Asgaros Forum and Mediathek Images

### ISSUE THREAD

**Issue by LastMohikkan** [GM-Alex/user-access-manager#123]
Hello, 

After I activated the latest update from UAM (2.1.1) I had the problem, that all categories from the Asgaros Forum (1.5.9) won't show up. The forum is behind a restricted area, where only users of a specific group can open it. 
Also I had problems with images from the medialibrary. I get the error message, that the image can't be found. If I look into the server hosting (FTP) I see all files. They also won't show up in the wordpress media library. 

Unfortunately I can't get it to work and so I decided to roll the UAM plugin back to the 2.0.13 version. This works for the forum, but unfortunately it doesn't work for the images. 

Regarding to the [other issue](https://github.com/GM-Alex/user-access-manager/issues/122), I think there is a general problem with media items. Please have a look at it. 
Thanks, 
Regards,
Alex

**Comment by GM-Alex** [comment]
I will have a look about the Asgaros form soon.

Media files can be only handled by the UAM if the appear at the Wordpress media library, so you have to add them there. I have improving the file handling on my todo list for the next big release (2.2) but don't expect it within the next weeks. I think a realistic time estimation for that is within the next two or three months because it's a quiet complex topic.

**Comment by GM-Alex** [comment]
Quick fix should be the following. Go to UAM > Settings > Taxonomies settings > Object type > Default > Hide empty > No. Can you confirm that this fixes your issue?

**Comment by Najad373** [comment]
This update to UAM also caused a problem with Asgaros Forum for me. UAM is now unreliable which is a shame because it was working OK. I recall that saying, 'If it ain't broke then don't fix it...' UAM wanted to change my .HTaccess file and database etc so I have now deleted it. If you can restore it to its previous version and get it working then I might install it again. At the moment is does not work with other far more important plugins.

**Comment by LastMohikkan** [comment]
Hi, 
Thanks for your fast reply and that you will have a look for the forum. 
I reinstalled the latest version and wanted to give it a try or to find out if any other setting will solve the problem. 
I also followed your tip with the taxonomy setting and now the forum and the images are shown correctly. Maybe the issue is caused with the update?

@Najad373 maybe a reinstall will also help you with the forum?

**Comment by GM-Alex** [comment]
@LastMohikkan No it's a issue with the user access manager. The UAM notice that the categories are empty and hides them, but the form categories should be handled by the UAM. I will prepare a new release with a fix for that tonight.

**Comment by LastMohikkan** [comment]
@GM-Alex Great job and thank you!

**Comment by GM-Alex** [comment]
@Najad373 What should I say to thinks like that:

> UAM is now unreliable which is a shame because it was working OK. I recall that saying, 'If it ain't broke then don't fix it...' UAM wanted to change my .htaccess file and database etc so I have now deleted it. If you can restore it to its previous version and get it working then I might install it again. At the moment is does not work with other far more important plugins.

I spending many hours of my free time to satisfy the "needs" of the users. There are more than 50000 plugins out there for Wordpress, how should I be guarantee that I will not break some of them in combination with UAM if I make an update? I know about the issue since seven hours and will make an fix today, I would say that is a quite fast reaction. In my opinion it's a shame getting treated like that as open source author. Many of my colleges stopped doing open source because of that. Maybe you get my point, that would make my day. :) 

And btw there is not other way than add UAM related tables to your database to create new object types like user groups, all other plugin doing that, could be the don't tell you. ;)

**Comment by Najad373** [comment]
Yes you are perfectly correct Alex and I sincerely apologise for saying those things. It's just that I panicked as my forum seemed to have disappeared. I have now reverted back to the previous version which is working fine. I will wait for you to correct the problem with this excellent plugin and help you anyway I can.
Regards
Phil
