### ISSUE TITLE
Lock files htaccess causes server overload (503)

### ISSUE THREAD

**Issue by wilmerschipper** [GM-Alex/user-access-manager#150]
Hello, 

After thoroughly testing with our VPS hosting provider, we finally figured out what caused our server to crash frequently. It turns out that is't caused by the htaccess in the uploads folder that is generated by UAM after 'Lock files' is enabled. 

Is anyone else experiencing this problem and is there a solution available? 

Thank you and best regards!

`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteRule ^([^?]*)$ /index.php?uamfiletype=attachment&uamgetfile=$1 [QSA,L]
RewriteRule ^(.*)\?(((?!uamfiletype).)*)$ /index.php?uamfiletype=attachment&uamgetfile=$1&$2 [QSA,L]
RewriteRule ^(.*)\?(.*)$ /index.php?uamgetfile=$1&$2 [QSA,L]
</IfModule>`

**Comment by GM-Alex** [comment]
The reason is not the htaccess it self but the fact that all files must delivered by the php process instead of the apache server to realise the file protection. The next version will add the option for xsendfile extension (https://tn123.org/mod_xsendfile/) which should solve this issue. xsendfile must be enabled on your server, please ask your hoster / sys admin if he can install it for you.

**Comment by GM-Alex** [comment]
2.1.7 xsendfile should fix this.
