### ISSUE TITLE
Forward to the requested URL after login not to the dashboard

### ISSUE THREAD

**Issue by lg2000github** [GM-Alex/user-access-manager#155]
I’ve got posts which are protected by the UAM and which are not shown on the blog. That works perfectly so far. I’ve got also URLs which I send to subscribers via email which lead directly to a protected post. If I follow one of these links they took me to a login page. That is good, too. But, after successfully login it takes me always to the users Dashboard instead of the linked article.

It would be nice if the user is taken directly to the requested URL after he logged in successfully. It is useless  to take the user to the dashboard.

**Comment by mystique2005** [comment]
I have 2.1.10 installed.  After I click the login link and login, I am still taken to the dashboard.  I went to UAM > Settings > Other Settings > Redirect User and set this to a custom URL of the home page.  Is this fix included in 2.1.10?  If so, how do I redirect a logged in user back to the home page so they can see the new navigation that contains pages they have access to?

**Comment by GM-Alex** [comment]
Please choose `To login page (wp-admin)` at the redirect settings.

**Comment by mystique2005** [comment]
From: Tiffany Amos [mailto:tiffany@mystiquesolutions.com] 
Sent: Tuesday, December 19, 2017 1:11 PM
To: 'GM-Alex/user-access-manager' <reply@reply.github.com>
Subject: RE: [GM-Alex/user-access-manager] Forward to the requested URL after login not to the dashboard (#155)

 

This still did not seem to work. Please let me know if I’m missing something.

 

1.	Screenshot of the redirect setting:  redirect.png 
2.	User with reader role goes to website to login: login.png and credentials.png
3.	After logging in, the user is redirected to the user’s profile instead of the Home page: profile.png

 

I want the user to be sent to the home page after they login - which will then have additional items under the Resident Login navigation:  access.png

**Comment by mystique2005** [comment]
Any comments on why the redirect may not be working as I specified above in the screenshots?

**Comment by GM-Alex** [comment]
So you want to redirect the user to a specified page instead of the origin page they are coming from, right? If so that feature isn't implemented. The "to login page" feature redirects the user after the login to the page he came from.

**Comment by lg2000github** [comment]
The feature worked fine for me after installing 2.1.10. But, in the meantime the behavior is still the same before installing the 2.1.10. Maybe it changed during a new version. It was such a great feature. Please reimplement this one. Or is there a chance to go back to 2.1.10?
