### ISSUE TITLE
E-Paper posts are not showing contents anymore

### ISSUE THREAD

**Issue by maschinentempel** [GM-Alex/user-access-manager#165]
Hi there,

I am using Wordpress 4.8.3 with UAM 2.1.7 and E-Paper 1.15 from David Nellessen.
After updating UAM from 1.2.7.4 to 2.1.7 I have an issue regarding the e-paper posts:

Before the update it worked like this: 
There are e-papers restricted to a user-group. When a user from this group is logged in, he has access to the e-paper files (PDF & FlipViewer).
Non-logged-in users could also see the list of e-paper posts with titles, covers, excerpts. They could also click on "read more" to visit the post single page to read the e-paper teasertext - after that would appear the PDF & Flipviewer links for subscribers, and for non-subscribers a note that they have to subscribe for having access to the e-paper files. The e-paper files themselves are also only accessable for subscribers. 

After the update it's now like that:
For logged-in users all works nicely as it should. But for non-logged-in users the list of e-papers are showing only the covers and instead of the excerpt there is already a message saying that content is restricted. When you click on "read more" you will be redirected to a login-form.

In the new updated UAM settings i did not change anything. Under post type settings > E-Paper there is set: use default = no, hide complete = no, hide title = no, e-paper content = (text that appears now instead of the excerpts), comments off.
 
Is there anything I have to do in order to make it working like before? 
I have an online dev-site running and would be able to give you access to it, if needed. 

Thanks a lot for your help!

**Comment by GM-Alex** [comment]
Hey please try the version of the next branch, that contains the "Show content before  tag" option for all post types. I think when you enable it for the epaper type it will work like before. Note that you have to run `composer install` when you are using the version directly from the branch.

**Comment by maschinentempel** [comment]
Thanks, that solved one part of the issue - the excerpts in the e-paper list view are now showing up again. But when a non-logged-in user click on "read more" it still leads to a login page. I would appreciate if you could look into this too, so that it really works like it did before.

**Comment by maschinentempel** [comment]
Like before means: E-Paper posts should be viewable by everyone, only the access to the e-paper files (pdf/flipviewer) should be restricted to the respective subscribers.

**Comment by GM-Alex** [comment]
The only reason that you will see the login page is if you have set up a redirect at the UAM settings to it. Could you check that first. So if this it not the case please disable all other plugins and test again, it could be an incompatibility with an other plugin. I'm not able to debug compatibility issues with plugins which aren't used by a big user base (E-Paper in this case), because I do this project in my free time and if I would begin that it will be a never ending story. I hope you will understand that. I've seen you are a developer too, so if you debug it by your own, find out what's needed to be changed and it will not break the logic for other users, just let me know and I will adjust it. Also if you need a new hook, that's no problem. I will close this until you have new information for me.

**Comment by maschinentempel** [comment]
Ah, the redirect setting was the missing thing. There was nothing checked by default (bug?), but after I set it to "No" everything worked as before again. Thank you so much for your help!
