### ISSUE TITLE
Separate download files from image files?

### ISSUE THREAD

**Issue by newoceans** [GM-Alex/user-access-manager#168]
Hi, is there a way to activate UAM for certain file types only - and so seperate access settings for download files from image files?

If I understand the plugin well, I can set access rules for media files. This way I can prevent certain user groups from downloading documents, like Word files, Excel Files, PDF's, etc. However, this access rule works for image files too? So, when displaying a page that includes images, these are evaluated against the access rules too?

I have the feeling (correct me if I'm wrong), that this slows down my pages, especially news pages with thumbnails of let's say 10 articles. Is that right?

If so, separating download files from image files would be an solution, may be? 

Or is it sufficient to set all access rules for images to 'Full acces'? And would this speed up page loading too?

ADDITION
========
It seems that restricting page access to certain groups, automatically restricts image files to those groups too. So then a bulk action to set access rules for all images to 'Full access' would be nice?

**Comment by GM-Alex** [comment]
If recursive locking is enabled the attached media content inherits the group. You can choose to exclude file types at the file settings if needed. Media content is managed the same like post, pages and so on is managed. And yes the file handling slow down your site because the php process must handle the content delivery. To fix that use xsendfile, see [https://github.com/GM-Alex/user-access-manager/wiki/Settings-%7C-File-settings#xsendfile](https://github.com/GM-Alex/user-access-manager/wiki/Settings-%7C-File-settings#xsendfile)

**Comment by newoceans** [comment]
Thnx for the info, Alexander!
