### ISSUE TITLE
menu disappears when not logged in!

### ISSUE THREAD

**Issue by muxip** [GM-Alex/user-access-manager#204]
UAM was working fine but since some time there’s something going wrong.
I have a website with pages for logged in users and public pages for not logged in users.
now if not logged in all public pages are not shown anymore, the menu has completely disappeared! I can go to the pages entering the direct url but in menu all pages have disappeared. When I deactivate the plugin, the menu returns like it should…but then all my restricted pages would be public, so this is not a solution…It’s a very frequented page, so this is really BAD.
Any hint what to do??? I already restored an old version of uam but it doesn’t change anything…
all pages which as marked as “full access” had been shown in the navigation primary menu. now, nothing is shown anymore

**Comment by muxip** [comment]
it's also not showing when I make a new menu with only non-restricted pages....

**Comment by GM-Alex** [comment]
I'm quite sure it's the same issue than #175. This issue comes from a WordPress bug, see https://core.trac.wordpress.org/ticket/42691 for more information. You have two options:

# Disable all plugins expect the UAM see if it works (it should work now) and start enabling the other plugins till it breaks. Now you know the plugin which causes the WordPress bug (the bug happens in combination of UAM and other plugins manipulating categories).
# Apply the patch provided at the WordPress ticket. Note: you have to do this after every update of WordPress until the WordPress core team fix the issue.

**Comment by hedbert** [comment]
Hi!

Could you please explain that in easier language? I have the same problem but don't understand what an "WordPress ticket" is :( 

I have tried to disable all plugins but the UAM still didn't work.

**Comment by muxip** [comment]
how do I apply the patch?

**Comment by muxip** [comment]
I also disabled other plugins without success

**Comment by GM-Alex** [comment]
You need to apply this patch: https://core.trac.wordpress.org/attachment/ticket/42691/42691.diff

**Comment by muxip** [comment]
I know, but how do I apply it?

**Comment by GM-Alex** [comment]
See the comment above and check the documentation link.

**Comment by muxip** [comment]
Patch is working, thanks!

**Comment by GM-Alex** [comment]
So since I'm not able to do anything about that until the WordPress core team will release a version with the fix, I will close this one.
