### ISSUE TITLE
Problem in connection with Elementor (PlugIn)

### ISSUE THREAD

**Issue by schmitty782** [GM-Alex/user-access-manager#213]
Hello.

I use ELEMTOR to create the pages. Once I've created the pages with ELEMENTOR, I can not just make them available to specific groups anymore. The pages will then be visible to all users. If I use the WordPress Editor again, the rights assignment works.

Regards
Christian

**Comment by lgs4gh** [comment]
I'm having the same issue. WP v4.9.4, Elementor (free) v1.9.5 and UAM 2.1.10. Pages edited with Elementor are visible to public no matter what. Plain WP pages with no Elementor work just fine with UAM.

Elementor has over half a million active installations, this is an extremely well used extension so hopefully a fix will be found.

cheers

**Comment by GM-Alex** [comment]
Works for me. I create a new post, edit the content with Elementor, publish the page, go back to the post assign the groups and it's locked... Also the order (so that the page is never public even for some secondes) create post, assign user group, save draft, edit content with Elementor works as expected.

**Comment by iamjohnpalencia** [comment]
Hi sir, i really love your plugin but it doesnt really work as intended when using elementor, i did some grouping for my "Products" privacy where group1 should not be able to see available product on group2 but that doesnt work because when i created a user even i click the "Group 1" radio button after saving it automatically save the access as "All" i mean i can see 3groups check now and cant edit it back because its disabled in the user settings

If possible to edit user access manually where can i do that ? i can email you for faster communication and also send you screenshot if possible for more details

thank you so much

**Comment by Larzans** [comment]
@iamjohnpalencia there is a great solution by @JboyJW in this thread https://github.com/GM-Alex/user-access-manager/issues/279#issuecomment-868951901

With his code snippet the header and footer are always shown, but the content part of Elementor is only shown to the users selected with UAM.
