### ISSUE TITLE
Redirect problem with custom login page

### ISSUE THREAD

**Issue by jtschulik** [GM-Alex/user-access-manager#28]
Hi,

I'm using UAM on a wordpress to protect full Posts/Pages from non-registered users.

When users hit a post/page, they should be redirected to a Custom-Login page which works great through Settings>Redirect User>Custom Page. 
The only problem is, after this redirect i can't find out the original requested URL, because a redirect already happened (from original URL to custom-login-page). 
Is there any way to find out the original requested URL, so i can redirect users back after they logged in? Maybe a hook or something?

Thanks in advance, king regards,
Jakob

**Comment by jtschulik** [comment]
No ideas on this issue? :(

**Comment by GM-Alex** [comment]
You could use the [LOGIN_FORM] tag, which should redirect the users to the origin page.

**Comment by jtschulik** [comment]
I guess you mean the wordpress shortcode? Unfortunately, that doesn't work, because it's also using the last redirect (which is to the custom-login-page)

Thank you!

**Comment by GM-Alex** [comment]
I will see to find a solution for version 2.1.0

**Comment by jtschulik** [comment]
yay! looking forward to it and thank you!

**Comment by Garconis** [comment]
I should mention that I have noticed a similar issue. I have it set to the locked page redirects the user to the Login page. My Login page is using Theme My Login. The issue is, that after the user logs in, it directs them to the homepage rather than the page they were trying to access. In addition to that, AFTER I try to manually access the locked page after logging in, it still redirects to the login page. 

Not sure if the log in redirect is somehow being cached for the session?

**Comment by agxer** [comment]
Hi any update on this? I am having the same issue and the plugin is pretty much useless with this redirect not working. I tried using the shortcode [LOGIN_FORM] and when the user logs in (even if they were already logged in in the frst place) they are redirected to the back end login page and not to the original page they were trying to access.

**Comment by GM-Alex** [comment]
I'm a little surprised/confused that using the default Wordpress login logic makes the plugin useless, but 2.1.0 will redirect you to the page you logged in.

**Comment by GM-Alex** [comment]
Duplicates #155. Will be changed at 2.1.10
