### ISSUE TITLE
Is UAM still supported??

### ISSUE THREAD

**Issue by jelleruben** [GM-Alex/user-access-manager#347]
Is UAM still supported? and is it still being developed?

Because is it posible to set the inlog widget to Dutch. 

Aand is it the follow thing possible:
When user A logs in he sees Menu A and when user B logs in he sees Menu B.

**Comment by matt-bernhardt** [comment]
I am also interested in whether this plugin is still supported. With no responses to recent posts in the plugin support forum, and the state of this issues queue, I'm unsure.

**Comment by GM-Alex** [comment]
Sorry for the late response. I only fix bugs, because the features the plugins offers are imho enough and hope the community which using the plugin for years can solve user questions within the support forum. I haven't currently much time to do more on the plugin, but if someone has improvements PRs are always welcome. I will try to review them within some days and release an update.

@jelleruben Translations can be contributed here: https://translate.wordpress.org/projects/wp-plugins/user-access-manager/ Dutch seems not fully translated, so just create an account and contribute the translations should fix the issue for you.
