### ISSUE TITLE
Images don't finish loading

### ISSUE THREAD

**Issue by amyschan** [GM-Alex/user-access-manager#47]
In version 2.0.4: When I turn on LOCK FILES, I noticed that images on a webpage don't finish loading. Seems it's timing out. Here's a screenshot showing a page that didn't finish loading the images. Note: These are 3 Jetpack galleries.

![uam-jetpack-gallery](https://cloud.githubusercontent.com/assets/900909/25469332/763dc44e-2ad0-11e7-8a7b-d11fcc114aa6.jpg)

When I refresh the page, I see that the logo didn't load in addition to some of the images. (Different from the first time.)

![uam-logo](https://cloud.githubusercontent.com/assets/900909/25469456/1c9a3282-2ad1-11e7-8a3d-f0c9d75d9d71.jpg)

Let me know if you need more info. Thank you!

**Comment by GM-Alex** [comment]
Are always the same files not loading? If yes how are the exact paths to the files including there names and could you provide me some of the not loading files? You could also try to integrate them to a single page and see if they working there.

**Comment by amyschan** [comment]
Each time it's different image files not loading.

Not sure what you mean by integrating them to a single page (sorry, hard to tell with all the blurring). All the images are on a single page.

If it helps, I can give you access to my staging environment so you can take a look. What is your email address?

**Comment by GM-Alex** [comment]
Please try version 2.0.5 (should be up within around 40 minutes). But I think that will not solve the problem, but maybe I'm wrong. Your problem seems for me more your server. To handle file access by php you need to pass the file through the php process which consumes much more resources than serving them by a http server. So if the files are anyway public I would suggest adjusting the .htaccess file, that these files are not handled by the UAM.

I could add a hook at the .htaccess file creation so your change will not get overwritten if you change the file setting at the backend (I'm guessing you are working for an agency so you should have access to a developer he will know what to do (: ).
