### ISSUE TITLE
CSS - Translate

### ISSUE THREAD

**Issue by NeuroGraphiX** [GM-Alex/user-access-manager#55]
Hi, your User Acvcess Manager ias really cool. Is possible modify your plugin? I want set .CSS in Frontend. Before i have do it in Dreamweaver. I have modify php files for have nice style and correct language. Now i see the plugin better but i dont know how set it. Can you add in Backend tags or texarea for set the CSS files? If you want i can help you with Italian language, if im ready for do it. I can work good in graphic but im not programmer. Thanks for your time.

**Comment by GM-Alex** [comment]
I will add a the possibility to use html for the content in the next minor release (2.1.0). This will give you the ability to use CSS tags there, see #63 

You can contribute to the translation here: https://translate.wordpress.org/locale/it/default/wp-plugins/user-access-manager

I will close this one because of issue #63
