### ISSUE TITLE
Problem with locked files

### ISSUE THREAD

**Issue by GM-Alex** [GM-Alex/user-access-manager#57]
Taken from #56 
> Using Lock files, it puts the site to very unusable state. For uploaded files, it works like a charm, but not for images. Media-libray is jamming, and even with super-admin rights, cannot see the images. Images did have options for access groups, but choosing them does nothing more for visibility. The media opening process was extremely slow. Even, if i choose for not lock images, did no improvement. So, the file and image locking goes side by side in practical? Or the .htaccess-file does not updated easily choosing files or images.

**Comment by GM-Alex** [comment]
@masimies Do have permalinks activated? If not could to activate them, save the UAM settings again and retry?

**Comment by masimies** [comment]
Yes, with /%postname%/

**Comment by GM-Alex** [comment]
Ok, could you provide me an url which is not working (no need of the full URL, but I need everything after the wp-content/).

**Comment by masimies** [comment]
Everything is working, without lock files. If i enable it, site is unusable due the media files. As instructed. If there is broken images, they have to browse again. But cannot browse, if site is jamming.
Thinking that if there could be choose file lock without images. But even excluding images, the effect is same still.
Here is the testfile folder structure, if this tells something:
https://teamsin.net/teamsinproj/wp-content/uploads/sites/11//testifaili.txt

Lock files works with that when activated well, but images went broken all.

**Comment by masimies** [comment]
Tested today with number of combinations. Outcome is following (With multisite installation and Super Cache):
Lock files on "all"
- Site speed drops dramatically, and information for it is:
"The following resources are missing a cache validator. Resources that do not specify a cache validator cannot be refreshed efficiently. Specify a Last-Modified or ETag header to enable cache validation for the following resources: (List of public images presented in frontpage)"

Lock files on "exclude images"
- No difference

Noticed same problem as with memebersite-plugin. With multisite installation, there have to use
/subsitename/ instead of subsitename/ in .htaccess-file. Then at least images are shown with combination Lock files on "exclude images"

Conclusion,
Locking files in all cases affects to cache images somehow. And that why the site slows down.
In this case, Super Cache does not have rights to cache images?

Tested 2-ways of caching, Rewrite- and PHP-modes. No difference.

**Comment by masimies** [comment]
More info for this.
.htacces file effect does not reach to subfolders. I think that this goes for single-site installations as well.
When there is additional folders like webcam, used for security camera alarm uploads. Images does not display in page, even the page has UAM-group added for access. Same goes for url-link thumbinal images in another folder under .htaccess protection.
This issue is on, even there is selected only assigned file-types. So images should be leave alone?
![filelock](https://cloud.githubusercontent.com/assets/17984661/25735732/f717c316-3175-11e7-9785-ffba9ee236ed.JPG)
So in common, cannot use File lock.
I'm really interest of this plugin, but cannot publish my site without more privacy. It is not the best solution to try find access-plugin for every single function separately. This is so close for one and only.
I hope if you have time to put for this issue.
I have advertised this plugin in many places all ready, that this could be the best solution for protecting content. ;-)

**Comment by masimies** [comment]
Hi,
This was not enhanced with 2.1.0 version. Or did i miss something?
Could it be possible with less effort, if there could be choice to choose the folder where to enable file lock?
Because by common, site public images in upload-folder has to be anyway without access restrictions. Using upload-folder puts admin to work every time, when site public media is changed.

**Comment by GM-Alex** [comment]
2.1.0 isn't released yet... :)

**Comment by GM-Alex** [comment]
This should be fixed with 2.0.12.

**Comment by masimies** [comment]
Hi, with new version there was no difference with functionality. Even i have now reinstalled whole site with a very clean installation. None of old plugin test leftovers in database or something else what could be conflicting.

**Comment by GM-Alex** [comment]
@masimies Have you tried to exclude images form the locking?

**Comment by masimies** [comment]
Yes i tried with all combinations.
If the htaccess-file is present, the images are broken. This happen at once if the file lock is active.
This would be easier, if you could assign file lock to your folder by self, like an option. Then, depending of design or what ever, function or not, plugin user could be assign file lock by his/her configuration. To the folder what needs protection. I do not still get it, why this is only for upload-folder, where are all media.
->Default to upload-folder, and can be changed freely in text-field, like "protected_files/"?

**Comment by GM-Alex** [comment]
It's like that because all the media normally is handled by the wordpress media gallery. And then UAM is able to decide if a user has access or not. It seems your media isn't handled by the wordpress media management and so UAM isn't able to grant you access. However the excluding images should at least work. Are you using nginx instead of apache?

**Comment by masimies** [comment]
I have apache.
It doesn't matter if i choose only files or not images. Activating file-lock (htaccess-file in) brakes the images visibility.
I have 2 choices for sub-site usage as membersite Ultimate Member and Supsystics Membership.
With both, the effect is same.
My target was, to create site with securing members files, but it seems to be too hard to achieve.
